version: "3.9"
services:
    postgres:
        image: postgres:15.2-alpine
        environment:
            POSTGRES_DB: "docker"
            POSTGRES_USER: "docker"
            POSTGRES_PASSWORD: "docker"
        ports:
            - "5432:5432"
